source-file ~/.tmux.conf

set -g prefix C-b
unbind-key C-a
bind-key C-b send-prefix

set -g status-style "bg=#45475a,fg=#cdd6f4"
set -g @catppuccin_status_modules_right "directory date_time session"
set -ag status-right " #[bg=#f38ba8,fg=#1e1e2e,bold] SSH "
